# Generated by Django 3.1.7 on 2021-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=20)),
                ('num1', models.IntegerField()),
                ('text2', models.CharField(max_length=20)),
                ('num2', models.IntegerField()),
            ],
        ),
    ]
